### ISSUE TITLE
validating values that are not in objects currently does not work

### ISSUE THREAD

**Issue by msteckyefantis** [vandium-io/lov#1]
For example, the following code:

``` .js
const lov = require( 'lov' );

const arr = [ 'a', 'b', 'c' ];

const schema = lov.array().required();

lov.validate( arr, schema );
```

throws an error. But it would be useful if you could validate schemas for individual values that are not within objects. Such are arrays, strings, or numbers.

**Comment by richardhyatt** [comment]
Added functionality to 1.1.0
